"""Utrecht Plane B world-scene tools: execute the utrecht-world-scene recipe
(world-scene-build process) and render the visual demo.

Inputs are copied into deep-agents/runs/<id>-worldscene/ and the build runs
there, so the canonical poc/scenario-runs directories are never modified.
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path
from typing import Any

import journal
from vizassets import leaflet_tags

HERE = Path(__file__).resolve().parents[1]
REPO_ROOT = HERE.parent
POC_DIR = REPO_ROOT / "poc"
RUNS_DIR = HERE / "runs"

_PAGE = """<!doctype html>
<html lang="nl">
<head>
<meta charset="utf-8">
<title>Utrecht world scene — {run_id}</title>
{leaflet_css}
<style>
  body {{ font-family: -apple-system, "Segoe UI", sans-serif; margin: 0; display: flex; }}
  #map {{ flex: 1; height: 100vh; background: #e8edf3; }}
  #side {{ width: 420px; height: 100vh; overflow-y: auto; padding: 14px 16px; box-sizing: border-box; background: #fafafa; border-left: 1px solid #ddd; }}
  h1 {{ font-size: 17px; margin: 4px 0 2px; }}
  .sub {{ color: #666; font-size: 12px; margin-bottom: 10px; }}
  .spec {{ border: 1px solid #ddd; border-radius: 8px; padding: 10px; margin-bottom: 10px; background: #fff; cursor: pointer; }}
  .spec.active {{ border-color: #2563eb; box-shadow: 0 0 0 2px rgba(37,99,235,.2); }}
  .delta {{ font-size: 20px; font-weight: 600; margin: 4px 0; }}
  .neg {{ color: #b91c1c; }} .pos {{ color: #15803d; }}
  .badge {{ display: inline-block; font-size: 11px; border-radius: 10px; padding: 1px 8px; background: #e5e7eb; margin-right: 4px; }}
  .gated {{ background: #fef3c7; }}
  details {{ margin-top: 6px; }} summary {{ font-size: 12px; color: #2563eb; cursor: pointer; }}
  .note {{ font-size: 12px; color: #444; }}
  .legend {{ font-size: 12px; margin-top: 8px; }}
  .sw {{ display: inline-block; width: 12px; height: 12px; border-radius: 3px; margin-right: 4px; vertical-align: -1px; }}
</style>
</head>
<body>
<div id="map"></div>
<div id="side">
  <h1>Utrecht world scene</h1>
  <div class="sub">scenario-run {run_id} · {spec_count} spec(s) · generated by the nLDT deep agents (Ollama, fully local)</div>
  <div class="legend"><span class="sw" style="background:#2563eb;opacity:.45"></span>control
    <span class="sw" style="background:#dc2626;opacity:.45"></span>scenario</div>
  {spec_cards}
</div>
{leaflet_js}
<script>
const DATA = {payload};
const map = L.map('map');
const controlLayer = L.featureGroup().addTo(map);
const scenarioLayer = L.featureGroup().addTo(map);
L.control.layers(null, {{'control': controlLayer, 'scenario': scenarioLayer}}).addTo(map);
let current = null;
function show(id) {{
  current = id;
  document.querySelectorAll('.spec').forEach(el => el.classList.toggle('active', el.dataset.id === id));
  controlLayer.clearLayers(); scenarioLayer.clearLayers();
  const d = DATA[id];
  L.geoJSON(d.control, {{style: {{color:'#2563eb', weight:1, fillColor:'#2563eb', fillOpacity:.25}}}}).addTo(controlLayer);
  L.geoJSON(d.scenario, {{style: {{color:'#dc2626', weight:1, fillColor:'#dc2626', fillOpacity:.28}}}}).addTo(scenarioLayer);
  map.fitBounds(controlLayer.getBounds().pad(0.05));
}}
document.querySelectorAll('.spec').forEach(el => el.addEventListener('click', () => show(el.dataset.id)));
show(Object.keys(DATA)[0]);
</script>
</body>
</html>
"""


def _workdir(scenario_run_id: str) -> Path:
    return RUNS_DIR / f"{scenario_run_id}-worldscene"


def _available_runs() -> list[str]:
    base = POC_DIR / "scenario-runs"
    return sorted(p.name for p in base.iterdir() if (p / "scenario-report.json").is_file())


def run_world_scene(scenario_run_id: str, hitl_approved: bool = False) -> dict[str, Any]:
    """Execute the utrecht-world-scene recipe for one poc/scenario-runs/<id>: build world-scene-specs.json (engine GeoJSON refs + gated Marble prompts) in deep-agents/runs/. poc/ itself is never modified. Call render_world_scene_demo afterwards for the visual demo."""
    import os

    if os.environ.get("NLDT_REQUIRE_INTAKE") == "1":
        from tools.artifacts import submitted_request

        if submitted_request() is None:
            journal.append(
                "error",
                "utrecht",
                "world-scene-build GEWEIGERD: geen gesubmiteerde, schema-geldige aanvraag — delegeer eerst intake (submit_request)",
            )
            raise ValueError(
                "Geen gesubmiteerde aanvraag: in ketenmodus moet de intake-specialist eerst "
                "submit_request aanroepen (schema-geldig OpportunityMapRequest) voordat de "
                "world scene gebouwd mag worden."
            )
    src = POC_DIR / "scenario-runs" / scenario_run_id
    if not (src / "scenario-report.json").is_file():
        raise FileNotFoundError(
            f"Unknown scenario run '{scenario_run_id}'. Runs with a scenario-report: "
            + ", ".join(_available_runs())
        )
    journal.append(
        "tool_call", "utrecht", f"run_world_scene('{scenario_run_id}') — world-scene-build"
    )
    work = _workdir(scenario_run_id)
    work.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src / "scenario-report.json", work / "scenario-report.json")
    if (src / "scenarios").is_dir():
        shutil.copytree(src / "scenarios", work / "scenarios", dirs_exist_ok=True)

    if str(POC_DIR) not in sys.path:
        sys.path.insert(0, str(POC_DIR))
    from pipeline.world_scene import write_world_scene_bundle

    bundle_path = write_world_scene_bundle(work, hitl_approved=hitl_approved)
    bundle = json.loads(bundle_path.read_text(encoding="utf-8"))
    journal.append(
        "tool_result",
        "utrecht",
        f"world-scene-specs.json built: {bundle['specCount']} spec(s) for {scenario_run_id}",
        viz={"kind": "worldscene", "runId": scenario_run_id},
    )
    return {
        "scenarioRunId": scenario_run_id,
        "bundlePath": str(bundle_path),
        "specCount": bundle["specCount"],
        "specs": [
            {
                "id": s["id"],
                "scenarioId": s["scenarioId"],
                "track": s["track"],
                "deltaKm2": s["headlineDeltaKm2"],
                "deltaPct": s["headlineDeltaPct"],
                "provenance": s["provenanceBasis"]["type"],
                "grounding": s["groundingStamp"],
                "marbleEnabled": s["marble"]["enabled"],
            }
            for s in bundle["specs"]
        ],
        "nextStep": "call render_world_scene_demo to produce the visual demo",
    }


def render_world_scene_demo(scenario_run_id: str) -> dict[str, Any]:
    """Render the interactive Leaflet demo (demo.html) from a built world-scene bundle: control vs scenario GeoJSON overlays per spec with headline deltas, provenance notes and gated Marble prompts. Run run_world_scene first. Returns the demo file path."""
    work = _workdir(scenario_run_id)
    bundle_path = work / "world-scene-specs.json"
    if not bundle_path.is_file():
        raise FileNotFoundError(f"No bundle for '{scenario_run_id}' — run run_world_scene first.")

    bundle = json.loads(bundle_path.read_text(encoding="utf-8"))
    data: dict[str, Any] = {}
    cards: list[str] = []
    for s in bundle["specs"]:
        control = json.loads((work / "scenarios" / "CONTROL.geojson").read_text(encoding="utf-8"))
        scen_path = work / "scenarios" / f"{s['scenarioId']}.geojson"
        scenario = json.loads(scen_path.read_text(encoding="utf-8")) if scen_path.is_file() else control
        data[s["id"]] = {"control": control, "scenario": scenario}
        delta = s["headlineDeltaKm2"]
        cls = "neg" if delta < 0 else "pos"
        cards.append(
            f"<div class='spec' data-id='{s['id']}'>"
            f"<div class='badge'>{s['id']}</div>"
            + ("<span class='badge gated'>Marble gated</span>" if not s["marble"]["enabled"] else "")
            + f"<div class='delta {cls}'>{delta:+.2f} km² ({s['headlineDeltaPct']:+.2f}%)</div>"
            f"<div class='note'>{s['mutationSummary']} · provenance: {s['provenanceBasis']['type']} · {s['groundingStamp']}</div>"
            f"<details><summary>Marble prompt (gated)</summary><div class='note'>{s['marblePrompt']}</div></details>"
            "</div>"
        )

    leaflet_css, leaflet_js = leaflet_tags()
    html = _PAGE.format(
        run_id=scenario_run_id,
        spec_count=bundle["specCount"],
        spec_cards="\n".join(cards),
        payload=json.dumps(data),
        leaflet_css=leaflet_css,
        leaflet_js=leaflet_js,
    )
    demo_path = work / "demo.html"
    demo_path.write_text(html, encoding="utf-8")
    journal.append(
        "tool_result", "utrecht", f"demo.html rendered → {demo_path}"
    )
    return {
        "demoPath": str(demo_path),
        "specCount": bundle["specCount"],
        "openWith": f"open {demo_path}",
    }
